__provider.tc.0=org.sterl.llmpeon.test.EclipseWorkspaceWriteFileToolTest
__provider.tc.1=org.sterl.llmpeon.test.EclipseWorkspaceReadFileToolTest
__provider.tc.2=org.sterl.llmpeon.test.JdtUtilDiskPathTest
__provider.tc.3=org.sterl.llmpeon.test.StandingOrdersBuilderTest
__provider.tc.4=org.sterl.llmpeon.test.EclipseGrepToolUnitTest
__provider.tc.5=org.sterl.llmpeon.test.PeonAiServiceTest
__provider.tc.6=org.sterl.llmpeon.test.EclipseCodeNavigationToolTest
__provider.tc.7=org.sterl.llmpeon.test.AbstractTest
classLoaderOrder=booterFirst
printBundles=false
printWires=false
redirectTestOutputToFile=false
reportsdirectory=/home/runner/work/eclipse-peon-ai/eclipse-peon-ai/org.sterl.llmpeon.test/target/surefire-reports
rerunFailingTestsCount=0
runOrder=filesystem
skipAfterFailureCount=0
testclassesdirectory=/home/runner/work/eclipse-peon-ai/eclipse-peon-ai/org.sterl.llmpeon.test/target/classes
testpluginname=org.sterl.llmpeon.test
testprovider=org.apache.maven.surefire.junitcore.JUnitCoreProvider
trimStackTrace=false
