source.. = src/
output.. = bin/
bin.includes = .,\
               plugin.xml,\
               META-INF/,\
               icons/,\
               fragment.e4xmi,\
               lib/llmpeon-core.jar,\
               lib/jackson-annotations.jar,\
               lib/jackson-core.jar,\
               lib/jackson-databind.jar,\
               lib/jspecify.jar,\
               lib/langchain4j.jar,\
               lib/langchain4j-core.jar,\
               lib/langchain4j-http-client.jar,\
               lib/langchain4j-http-client-jdk.jar,\
               lib/langchain4j-ollama.jar,\
               lib/langchain4j-google-ai-gemini.jar,\
               lib/langchain4j-open-ai.jar,\
               lib/jtokkit.jar,\
               lib/langchain4j-mistral-ai.jar,\
               lib/langchain4j-anthropic.jar,\
               lib/langchain4j-mcp.jar,\
               lib/opennlp-tools.jar,\
               lib/slf4j-api.jar,\
               resources/,\
               lib/flexmark.jar,\
               lib/flexmark-ext-emoji.jar,\
               lib/flexmark-ext-gfm-strikethrough.jar,\
               lib/flexmark-ext-ins.jar,\
               lib/flexmark-ext-superscript.jar,\
               lib/flexmark-ext-tables.jar,\
               lib/flexmark-ext-wikilink.jar,\
               lib/flexmark-html2md-converter.jar,\
               lib/flexmark-jira-converter.jar,\
               lib/flexmark-util.jar,\
               lib/flexmark-util-ast.jar,\
               lib/flexmark-util-builder.jar,\
               lib/flexmark-util-collection.jar,\
               lib/flexmark-util-data.jar,\
               lib/flexmark-util-dependency.jar,\
               lib/flexmark-util-format.jar,\
               lib/flexmark-util-html.jar,\
               lib/flexmark-util-misc.jar,\
               lib/flexmark-util-options.jar,\
               lib/flexmark-util-sequence.jar,\
               lib/flexmark-util-visitor.jar,\
               lib/jsoup.jar,\
               lib/langchain4j-azure-open-ai.jar,\
               lib/azure-ai-openai.jar,\
               lib/azure-core.jar,\
               lib/azure-core-http-netty.jar,\
               lib/azure-json.jar,\
               lib/azure-xml.jar,\
               lib/reactive-streams.jar,\
               lib/netty-resolver.jar,\
               lib/netty-common.jar,\
               lib/netty-handler.jar,\
               lib/netty-transport.jar,\
               lib/reactor-core.jar,\
               lib/reactor-netty-core.jar,\
               lib/reactor-netty-http.jar,\
               lib/netty-resolver-dns-classes-macos.jar,\
               lib/netty-resolver-dns-native-macos-osx-x86_64.jar,\
               lib/netty-buffer.jar,\
               lib/netty-codec.jar,\
               lib/netty-codec-dns.jar,\
               lib/netty-codec-http.jar,\
               lib/netty-codec-http2.jar,\
               lib/netty-codec-socks.jar,\
               lib/netty-handler-proxy.jar,\
               lib/netty-resolver-dns.jar,\
               lib/netty-tcnative-boringssl-static.jar,\
               lib/netty-tcnative-boringssl-static-linux-aarch_64.jar,\
               lib/netty-tcnative-boringssl-static-linux-x86_64.jar,\
               lib/netty-tcnative-boringssl-static-osx-aarch_64.jar,\
               lib/netty-tcnative-boringssl-static-osx-x86_64.jar,\
               lib/netty-tcnative-boringssl-static-windows-x86_64.jar,\
               lib/netty-tcnative-classes.jar,\
               lib/netty-transport-classes-epoll.jar,\
               lib/netty-transport-classes-kqueue.jar,\
               lib/netty-transport-native-epoll-linux-x86_64.jar,\
               lib/netty-transport-native-kqueue-osx-x86_64.jar,\
               lib/netty-transport-native-unix-common.jar,\
               lib/jackson-datatype-jsr310.jar
